# Generated by Django 5.1 on 2024-08-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="姓名")),
                ("age", models.SmallIntegerField(null=True, verbose_name="年龄")),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                ("address", models.CharField(max_length=255, verbose_name="地址")),
                ("phone", models.CharField(max_length=255, verbose_name="手机号")),
                (
                    "gender",
                    models.CharField(
                        choices=[(1, "Male"), (0, "Female")],
                        max_length=255,
                        verbose_name="性别",
                    ),
                ),
                ("role", models.CharField(max_length=255, verbose_name="角色")),
                ("status", models.CharField(max_length=255, verbose_name="状态")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_online_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后登录时间"),
                ),
            ],
        ),
    ]
